jenkins:
  restart: always
  image: slsay/docker-jenkins:2.0.2
  volumes:
    - ~/srv/docker/jenkins/jenkins:/var/jenkins_home
  ports:
    - 8080:8080
    - 50000:50000

mysql:
  restart: always
  image: slsay/docker-mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=redmine

redmine:
  restart: always
  image: slsay/docker-redmine:latest
  links:
    - mysql:mysql
  volumes:
    - ~/srv/docker/redmine/redmine:/home/redmine
  ports:
    - 8080:8080
    
sonar:
  image: sonarqube:latest
  ports:
    - 9000:9000
    - 9092:9092
  
proxy:
  image: slsay/docker-proxy:latest
  links:
   - redmine:redmine
   - jenkins:jenkins
   - sonar:sonar
  ports:
    - "80:80"
